### ISSUE TITLE
Browser Version

### ISSUE THREAD

**Issue by 1wheel** [aplbrain/npyjs#10]
This works great in the browser without the [fetch import](https://github.com/aplbrain/npyjs/blob/master/index.js#L1). I had to a do a little fiddling to figure that out and it looks @Fil [did too](https://observablehq.com/@fil/npyjs).

Have you considered publishing the decoding function alone so this library can be used directly in the browser?

**Comment by j6k4m8** [comment]
I don't have that on my roadmap right now, but if you were interested in PR'ing a fix I'd love to review/merge :)

Is `fetch` giving you an error/failure or is it just unnecessary for your use? (I wanted to keep things server+browser-friendly but this may not be the right way to go about doing that.)

**Comment by j6k4m8** [comment]
Closed in #14!
