### ISSUE TITLE
TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by lixiaofa-lab** [aplbrain/npyjs#30]
how to convert  dtype: 'float64',
  data: Float64Array(256)   into Array

**Comment by j6k4m8** [comment]
Hey @lixiaofa-lab! Can you post the code that you tried, and I'll see if I can help debug?

**Comment by lixiaofa-lab** [comment]
Thank you. I was trying to convert the data from Float64Array(256) to a normal javaScript array, but MDN doesn't seem to have that way

**Comment by j6k4m8** [comment]
You should be able to use `Array.from`:

```js
let typedArray = new Float64Array(256);
let normalArray = Array.from(typedArray);
```

Please do reopen this issue (or file another one) if you have any further trouble with the library :)
