### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by Ricerob** [aplbrain/npyjs#32]
I'm using the code from this library in a TypeScript/ Deno environment. It'd be nice if there was a possible TS implementation. If not, I can take a shot at it! I have a rough, typed implementation. Let me know what you think and how I can test/ help implement this.

**Comment by j6k4m8** [comment]
Hi @Ricerob!! So glad to hear the project has been helpful to you! Would love to merge a TS contribution if you are willing to make one, as long as we can still compile it down to share on npm as a JS library for JS users! ...just haven't had the engineering bandwidth to do myself... Super excited to see!

**Comment by Ricerob** [comment]
Thanks @j6k4m8 ! I'm super new to TypeScript and packaging modules.. any chance you could point me in the right direction for something like this?
