### ISSUE TITLE
Functionality to allow ArrayBuffer inputs along with file path

### ISSUE THREAD

**Issue by AdityaSarwade** [aplbrain/npyjs#35]
Hey, @j6k4m8 I've used your package in a few packages and I think it is a life-saver.

I faced an issue when I wanted to parse and open a .npy file from and ArrayBuffer in TypeScript.
I identified that the load function internally creates an ArrayBuffer which stores the result of the fetch request.

It would be really helpful if we could bypass this part of the code when the passed argument is already an ArrayBuffer.

Although I am not as experienced as my peers, I'm submitting a PL as it might be a useful addition.

**Comment by j6k4m8** [comment]
Yes, love it!! thank you for #36!!
