### ISSUE TITLE
Release including types

### ISSUE THREAD

**Issue by rmorshea** [aplbrain/npyjs#41]
Thanks for this awesome package!

The current release doesn't include any of the types at found [here](https://github.com/aplbrain/npyjs/blob/57242b82233a8e42c31028bdecbd91091a4f2b13/index.d.ts). A quick release that includes these types would be great. Currently we just copy-pasted that file into our project.

**Comment by j6k4m8** [comment]
Should be fixed now @rmorshea, thank you for the bump! Let me know if [v0.6.0](https://www.npmjs.com/package/npyjs) works for you!

**Comment by rmorshea** [comment]
Thanks! Looks like that worked for us.

**Comment by j6k4m8** [comment]
Awesome, glad to hear it!
