### ISSUE TITLE
Int16 dtype

### ISSUE THREAD

**Issue by esperanc** [aplbrain/npyjs#6]
Thanks for your code! I found, however, that Int16 files were not supported. This can be fixed easily enough by including the following dtype

   "<i2": {
      name: "int16",
      size: 16,
      arrayConstructor: Int16Array,
    },

Thanks

**Comment by j6k4m8** [comment]
Thanks @esperanc! Did you have a particular use-case in mind here? I've added int16 in #7. I'll test it shortly (and then merge) but if you have a use-case and would like to give it a whirl before I merge to master, I'd be happy to wait to make sure it works for you!

**Comment by esperanc** [comment]
Thanks Jordan. Yes, I used your code in a medical image visualizer you can
access here: https://observablehq.com/d/202d1615da944357

It worked perfectly!

Best Regards

--Claudio

**Comment by j6k4m8** [comment]
Excellent! So glad it's working for you. Love the visualizer, too! :)

**Comment by j6k4m8** [comment]
Fixed in #7
